### ISSUE TITLE
Add support for semantic manifest files

### ISSUE THREAD

**Issue by MiConnell** [yu-iskw/dbt-artifacts-parser#105]
It would be great if this library supported [semantic_manifest](https://docs.getdbt.com/docs/dbt-cloud-apis/sl-manifest) parsing.

**Comment by yu-iskw** [comment]
@MiConnell Please feel free to re-open the issue. It would be hard to support the semantic manifest artifact in dbt-artifacts-parser as of now, since the JSON schema isn't publicly available. 

https://github.com/yu-iskw/dbt-artifacts-parser/pull/106#issuecomment-2327930002
