### ISSUE TITLE
Validation errors for dbt > 1.4.1

### ISSUE THREAD

**Issue by dlawin** [yu-iskw/dbt-artifacts-parser#32]
FYI if you're noticing manifests not parsing for dbt > 1.4.1

https://github.com/dbt-labs/dbt-core/issues/7119

**Comment by OnkarVO7** [comment]
@dlawin @yu-iskw we are facing the same issue. Is there any update to currently fix this?

**Comment by yu-iskw** [comment]
Thank you for opening the issue. I will look into it tomorrow.

**Comment by yu-iskw** [comment]
@dlawin @OnkarVO7 Can you check if v0.2.5 behaves as you expect or not? I have re-generate the pydantic class of manivest v8 with the latest JSON schema in the dbt-core repository.

**Comment by OnkarVO7** [comment]
@yu-iskw it is working for me now with the `v0.2.5`

**Comment by dlawin** [comment]
I will test later today, really appreciate it!

**Comment by dlawin** [comment]
> @dlawin @OnkarVO7 Can you check if v0.2.5 behaves as you expect or not? I have re-generated the pydantic class of manivest v8 with the latest JSON schema in the dbt-core repository.
> 
> https://github.com/yu-iskw/dbt-artifacts-parser/releases/tag/v0.2.5

works great ty!
