### ISSUE TITLE
Support pydantic 2

### ISSUE THREAD

**Issue by yu-iskw** [yu-iskw/dbt-artifacts-parser#62]
As of this writing, we support only pydantic v1. It would be good to support pydantic v2 as well.

**Comment by yu-iskw** [comment]
link
https://github.com/yu-iskw/dbt-artifacts-parser/pull/66#issuecomment-1822097260

**Comment by yu-iskw** [comment]
@OnkarVO7 Let me ask you a question about pydantic. Do you have any plan to use pydantic 2 in OpenMetadata? Otherwise, do any other connectors still need pydantic 1 due to the dependency?

As you may know, pydantic 2 was released. I am wondering how we can support both major versions of pydantics. Or I just want to know we can migrate to pydantic 2 without deep consideration. I haven't investigated if pydantic 2 is fully compatible to pydantic 1 or not. I'm sure OpenMetadata is the largest project which uses the python package.

I left a little bit in my mind at the following link:
https://github.com/yu-iskw/dbt-artifacts-parser/pull/66#issuecomment-1822097260

**Comment by OnkarVO7** [comment]
@yu-iskw we do plan on migrating to pydantic v2 in the near future, probably in the next couple of releases.
Do let us know your plans on supporting this we'll also plan accordingly

**Comment by yu-iskw** [comment]
@OnkarVO7 Thank you for sharing. I don't have a clear plan. But, I would love to definitely support pydantic 2 before the migration on the OpenMetadata side. I will make a list of potential approaches to satisfy requirements I am thinking.

**Comment by yu-iskw** [comment]
Besides, I've opened a discussion to get advice from the pydantic community.

https://github.com/pydantic/pydantic/discussions/8203

**Comment by potiuk** [comment]
Hellow @yu-iskw - lack of Pydantic v2 support blocks some of our users from upgrading to latest line of Airflow 2.8. Is there anything we can do to help with the migration? Pydantic v2 is now used by pretty much every other dependency we use (and we have 670+ of them altogether). so it would be cool if Pydantic v2 is also supported. 

Do you have a clearer plan by now currently ?

**Comment by yu-iskw** [comment]
Migrate it to pydantic 2

https://github.com/yu-iskw/dbt-artifacts-parser/pull/78
