### ISSUE TITLE
Using local copies of artifact schemas for validation causes breakage

### ISSUE THREAD

**Issue by psygnoser** [yu-iskw/dbt-artifacts-parser#99]
Recently the package `dbt-common`, which is an dependency of `dbt-core` has updated from `1.5.0` to `1.6.0`. This introduced schema changes in `mainfest.json` which in turn caused this package to break, since it's using a local copy of the `V12` schema which has meanwhile updated to include the new schema changes (see [here](https://schemas.getdbt.com/dbt/manifest/v12.json)). 

At first I've actually opened an issue with them (please see [here](https://github.com/dbt-labs/dbt-common/issues/170) ), but apparently their policy is, that changes to the schemas are allowed to happen in between versions, which means your package might fail at any time (when any `dbt-core` dependancies update etc), even if no new artifact schema version was released.

**Comment by jochemvandooren** [comment]
Just wanted to say that I also have this problem. I am unable to use this package anymore because of the changes mentioned.

**Comment by psygnoser** [comment]
@jochemvandooren The workaround is to lock `dbt-common` to version `1.5.0`.

**Comment by jochemvandooren** [comment]
> @jochemvandooren The workaround is to lock `dbt-common` to version `1.5.0`.

Yes, sorry I managed fix it indeed :+1: . Not the desired solution though!

**Comment by yu-iskw** [comment]
Please feel free re-open this, if we still need to address.
